# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# Language of the webpage
lang: en

# Universal time zone
timezone: UTC

# SEO tag settings
title: Keyhan Khosravifard Blog
tagline: Exploring Web GIS Technologies
description: Personal blog by Keyhan Khosravifard about Web GIS development, tools, and tutorials.

# Your site URL and baseurl
url: "https://keyhangis.github.io"
baseurl: "/blog"

# github:
#   username: keyhangis
social:
  name: Keyhan Khosravifard
  email: keyhan.khosravifard@gmail.com
  links:
    - https://github.com/keyhangis
    - https://t.me/keyhangis
    - https://www.linkedin.com/in/keyhangis
    - https://www.youtube.com/@keyhangis

webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

analytics:
  google:
    id:
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

pageviews:
  provider:

# Theme appearance
theme_mode: light

cdn: "https://chirpy-img.netlify.app"

# Optional avatar (replace with your image path if needed)
avatar: "/assets/img/my-avatar.jpg"

# Optional preview image for social sharing
social_preview_image:

# Global Table of Contents toggle
toc: true

comments:
  provider:
  disqus:
    shortname:
  utterances:
    repo:
    issue_term:
  giscus:
    repo:
    repo_id:
    category:
    category_id:
    mapping:
    strict:
    input_position:
    lang:
    reactions_enabled:

assets:
  self_host:
    enabled:
    env:

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

paginate: 10

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
